[package]
name = "locus-core"
description = "Shared types and error definitions for Locus"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
dirs = { workspace = true }
blake3 = { workspace = true }
roaring = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
