[package]
name = "locus-bitmap"
description = "BitmapStore trait and implementations (LMDB/heed first)"
version.workspace = true
edition.workspace = true

[dependencies]
locus-core = { workspace = true }
roaring = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
heed = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
